## Secret containing the MySQL root password
##
## This secret is used by the MySQL deployment to set the root
## password for the database server.  The value here is a base64‑encoded
## representation of the password "secret".  In a real project you
## should generate a stronger password and store it in a more secure
## manner (for example using Azure Key Vault or Kubernetes secrets
## manager).  The name of the key (`MYSQL_ROOT_PASSWORD`) matches
## the environment variable expected by the official MySQL image.

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: c2VjcmV0  # base64 for "secret"