using System.ComponentModel.DataAnnotations;

namespace DotnetApi.Models
{
    /// <summary>
    /// Represents a single item in the list. This entity is persisted to the
    /// underlying MySQL database via Entity Framework Core.
    /// </summary>
    public class Item
    {
        /// <summary>
        /// Primary key. The value is generated by the database.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Name of the item. This property is required.
        /// </summary>
        [Required]
        public string Name { get; set; } = string.Empty;
    }
}