
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY *.csproj ./
RUN dotnet restore
COPY . .
RUN dotnet publish -c Debug -o /app/publish

#FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
#WORKDIR /app
#COPY --from=build /app/publish .
#EPOSE 8080
#ENTRYPOINT ["dotnet", "App.dll"]
